In [20]:
import pandas as pd

# Load the training and testing datasets
df_train = pd.read_csv('/content/train_KNN.csv')
df_test = pd.read_csv('/content/test_KNN.csv')

print("Training data head:")
display(df_train.head())
print("\nTesting data head:")
display(df_test.head())

Training data head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Testing data head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Next, we'll separate the features (X) from the target variable (y) for both the training and testing sets. We're assuming the last column is the target variable. You might need to adjust the column selection if your target is named differently or located elsewhere.

In [9]:
# Assuming 'Survived' is the target variable
y_train = df_train['Survived']
X_train = df_train.drop('Survived', axis=1)

y_test = df_test['Survived']
X_test = df_test.drop('Survived', axis=1)

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (891, 11)
Shape of y_train: (891,)
Shape of X_test: (418, 11)
Shape of y_test: (418,)

First, let's load the data from `train_KNN.csv` and `test_KNN.csv` into pandas DataFrames. We'll assume the last column of your dataset is the target variable.

In [11]:
import pandas as pd

# Load the training and testing datasets
df_train = pd.read_csv('/content/train_KNN.csv')
df_test = pd.read_csv('/content/test_KNN.csv')

print("Training data head:")
display(df_train.head())
print("\nTesting data head:")
display(df_test.head())

Training data head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Testing data head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Next, we'll separate the features (X) from the target variable (y) for both the training and testing sets. We're assuming the last column is the target variable. You might need to adjust the column selection if your target is named differently or located elsewhere.

In [15]:
# Assuming the last column is the target variable
X_train = df_train.iloc[:, :-1]
y_train = df_train.iloc[:, -1]

X_test = df_test.iloc[:, :-1]
y_test = df_test.iloc[:, -1]

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (891, 11)
Shape of y_train: (891,)
Shape of X_test: (418, 11)
Shape of y_test: (418,)

First, let's clean up the features. We'll drop columns that are typically not useful for machine learning models and might contain non-numeric data or unique identifiers, such as 'PassengerId', 'Name', 'Ticket', and 'Cabin'.

In [16]:
X_train = X_train.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
X_test = X_test.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

print("X_train columns after dropping:", X_train.columns.tolist())
print("X_test columns after dropping:", X_test.columns.tolist())

X_train columns after dropping: ['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
X_test columns after dropping: ['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']

First, let's load the data from `train_KNN.csv` and `test_KNN.csv` into pandas DataFrames.

In [ ]:
import pandas as pd

df_train = pd.read_csv('/content/train_KNN.csv')
df_test = pd.read_csv('/content/test_KNN.csv')

print("Training data head:")
display(df_train.head())
print("\nTesting data head:")
display(df_test.head())

Next, we'll separate the target variable ('Survived') from the features. This ensures 'Survived' is in `y` and 'Embarked' remains in `X` for further processing.

In [ ]:
y_train = df_train['Survived']
X_train = df_train.drop('Survived', axis=1)

y_test = df_test['Survived']
X_test = df_test.drop('Survived', axis=1)

print("Shape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Now, let's clean up the features by dropping columns that are not useful for our model, such as 'PassengerId', 'Name', 'Ticket', and 'Cabin'.

In [ ]:
X_train = X_train.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
X_test = X_test.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

print("X_train columns after dropping:", X_train.columns.tolist())
print("X_test columns after dropping:", X_test.columns.tolist())

Next, we'll handle missing values. For numerical columns ('Age', 'Fare'), we'll use the median. For categorical columns like 'Embarked', we'll use the mode (most frequent value).

In [ ]:
import numpy as np

# Convert categorical features into dummy variables
X_train = pd.get_dummies(X_train, columns=['Sex', 'Embarked'], drop_first=True, dtype=int)
X_test = pd.get_dummies(X_test, columns=['Sex', 'Embarked'], drop_first=True, dtype=int)

# Align columns - crucial for consistent feature sets between train and test
# Add missing columns to X_test with 0, and remove extra columns from X_test
missing_cols_train = set(X_train.columns) - set(X_test.columns)
for c in missing_cols_train:
    X_test[c] = 0

missing_cols_test = set(X_test.columns) - set(X_train.columns)
for c in missing_cols_test:
    X_test.drop(c, axis=1, inplace=True)

X_test = X_test[X_train.columns] # Ensure the order of columns is the same

print("X_train head after one-hot encoding:")
display(X_train.head())
print("\nX_test head after one-hot encoding:")
display(X_test.head())

Now that our data is clean and all numerical, we can scale the features using `StandardScaler`. This is an important preprocessing step for many machine learning algorithms, ensuring all features contribute equally.

In [26]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
schaler = StandardScaler()

# Fit the scaler on the training data and transform both training and testing data
scaled_X_train = schaler.fit_transform(X_train)
scaled_X_test = schaler.transform(X_test)

print("Scaled X_train (first 5 rows):\n", scaled_X_train[:5])
print("\nScaled X_test (first 5 rows):\n", scaled_X_test[:5])

ValueError: could not convert string to float: 'male'

### Decision Tree Classifier

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Initialize and train the Logistic Regression model
log_reg = LogisticRegression(random_state=42)
log_reg.fit(scaled_X_train, y_train)

# Predict and evaluate
y_pred_log = log_reg.predict(scaled_X_test)
log_accuracy = accuracy_score(y_test, y_pred_log)
print(f"Logistic Regression Accuracy: {log_accuracy:.4f}")

NameError: name 'scaled_X_train' is not defined

### Decision Tree Classifier

In [24]:
from sklearn.tree import DecisionTreeClassifier

# Initialize and train the Decision Tree model
dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(scaled_X_train, y_train)

# Predict and evaluate
y_pred_dt = dt_clf.predict(scaled_X_test)
dt_accuracy = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")

NameError: name 'scaled_X_train' is not defined

### Model Performance Comparison

In [23]:
import pandas as pd

# Create a DataFrame to compare accuracies
comparison_df = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree'],
    'Accuracy': [log_accuracy, dt_accuracy]
})

print("\nModel Performance Comparison:")
display(comparison_df.sort_values(by='Accuracy', ascending=False))

NameError: name 'log_accuracy' is not defined